### ISSUE TITLE
Fishing Made Better - Fillet Knife - Broken Recipe

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft#5] opened 2022-01-17 00:26 UTC
**Describe the bug**
Fishing Made Better has a recipe that takes it's **fillet knife** + **any fish** and output either a **fish slice** (#8606) or a special item due to rare fish (IE Cave Trout > Coal)
Bug is that the fish added by **Advanced Fishing** do not work with this recipe, even though JEI claims that it does.

**Screenshots**
![image](https://user-images.githubusercontent.com/97805739/149684211-c302ecae-5613-4e8f-a313-2e150f186172.png)

**Vanilla** Salmon works.
![image](https://user-images.githubusercontent.com/97805739/149684226-09467c7c-cd00-4cc6-a23f-adb5c12e9637.png)

**Advanced Fishing** fish do not.
![image](https://user-images.githubusercontent.com/97805739/149684243-094e9891-9ffb-46b6-8ddb-9b480558b009.png)
![image](https://user-images.githubusercontent.com/97805739/149684249-e82f68d1-c17c-421f-a112-e5d2cfea48a9.png)
![image](https://user-images.githubusercontent.com/97805739/149684254-72d58c8b-7612-4e56-9cc3-25dd8fbbc522.png)

**Clientside information (please complete the following information):**
 - Düncraft Version [011322a]

**Comment by Pingu-Pox** [comment] 2022-03-16 23:32
I submitted an issue to the mod dev to look at
https://github.com/TheAwesomeGem/fishing-made-better/issues/6

If the issue is not resolved within a few days (or the update after next), then I will remove all recipes and add them manually.

**Comment by Pingu-Pox** [comment] 2022-03-17 19:58
https://github.com/TheAwesomeGem/fishing-made-better/issues/6
Issue is that fish need to be caught using the FishingMadeBetter rods, so I will be removing the other rods.

Update live in next version.

**Closed as completed by Pingu-Pox** 2022-03-17 19:58 UTC
Labels: bug, Resolved
